[package]
name = "fee"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
dirs = "6.0.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
